name: Update Resume Gist

on: push

jobs:
  update-resume:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: npm run gen-pdf

      - name: Generate HTML files
        run: npm run gen-html

      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-html
          compression-level: 0
          path: |
            resume/*

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: BalazsSevecsek/BalazsSevecsek
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          path: target-repo

      - name: Copy Generated Files
        run: |
          mkdir -p target-repo/resume 
          cp -R resume/* target-repo/resume
          cp -R balazs_sevecsek.jpg target-repo/resume

      - name: Commit files
        run: |
          cd target-repo
          git add .
          git config --local user.email "github@action.com"
          git config --local user.name "github-action"
          git commit -a -m "Add changes"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: BalazsSevecsek/BalazsSevecsek
          branch: main
          directory: target-repo
          github_token: ${{ secrets.PAT }}

      # - name: Update Resume Gist
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     gist_id: dbf716e7a1aac924f69e2b3eaf42d7a2
      #     file_path: resume.json
