name: Update Resume Gist

on: push

jobs:
  update-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Generate PDF file
      - name: Generate PDF
        run: npm run gen-pdf

      # Generate HTML files
      - name: Generate HTML files
        run: npm run gen-html

      # Upload HTML files as artifacts
      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-html
          path: |
            resume/*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./resume

      - name: Update Resume Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: dbf716e7a1aac924f69e2b3eaf42d7a2
          file_path: resume.json
