name: Update Resume Gist

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-resume:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: npm run gen-pdf

      - name: Generate HTML files
        run: npm run gen-html

      - name: Upload HTML files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-html
          compression-level: 0
          path: |
            resume/*

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload generated files

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "resume"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Update Resume Gist
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     gist_id: dbf716e7a1aac924f69e2b3eaf42d7a2
      #     file_path: resume.json
